name: Build-Versao-Docker

on:
  push:
    branches:
    - versao-docker
  pull_request:
    branches:
    - versao-docker

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    
    - name: Teste Request
      run: |
        CODE=`curl --write-out '%{http_code}' \
            --silent \
            --output /dev/null \
            --request GET \            
            --url 'https://www.google.com' \
            `
    
        if [ $CODE!="200" ] 
        then
            echo "FAILURE"
        else
            echo "SUCCESS"
        fi
    
    
