name: Build-Versao-Docker

on:
  push:
    branches:
    - versao-docker
  pull_request:
    branches:
    - versao-docker

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Inicia containers
      run: docker-compose -f "./docker/docker-compose.yml" -f "./docker/docker-compose.override.yml" up -d --build

    - name: Verifica Conatainers
      id: check  
      run: docker ps        
         
    - name: Parar containers
      run: docker-compose --f "./docker/docker-compose.yml" -f "./docker/docker-compose.override.yml" down
