name: Build-Versao-Docker

on:
  push:
    branches:
    - versao-docker
  pull_request:
    branches:
    - versao-docker

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    
    - name: Teste Request
      run: http_response=$(curl http://www.google.com.br -o /dev/null -w '%{http_code}\n' -s); if [ $http_response != "200" ]; then echo "Ooooppssss container não subiu" ; else echo "Manda bala amigão tudo certo ;) heHehEhehEHHEH"; fi;
    
    
